query fetch($login: String!) {
  user(login: $login) {
    lifetimeReceivedSponsorshipValues(first: 100, orderBy: {field: LIFETIME_VALUE, direction: DESC}) {
      nodes {
        amountInCents
        sponsor {
          ... on User { login }
          ... on Organization { login }
        }
      }
    }
  }
}
