query fetch($cursor: String!) {
    coupons(first: 100, after: $cursor) {
        totalCount
        pageInfo {
            endCursor
            hasNextPage
        }
        edges {
            node {
                code
                state
            }
        }
    }
}
