strict: true

site_name: junior.guru
site_url: https://junior.guru/

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
  anchors: warn

markdown_extensions:
  - toc:
      toc_depth: "2-2"
      permalink: "#"
      permalink_title: Odkaz na tuto sekci
      toc_class: "document-toc"
  - tables
  - fenced_code
  - attr_list

theme:
  name: null
  custom_dir: theme/
  static_templates:
    - 404.html

hooks:
  - hooks.py

plugins:
  - gen-files:
      scripts:
        - generators.py
  - awesome-nav
