query fetch($cursor: String!) {
  members(first: 100, after: $cursor, state: ACTIVE) {
    pageInfo {
      endCursor
      hasNextPage
    }
    edges {
      node {
        email
        subscriptions {
          createdAt
        }
      }
    }
  }
}
