query fetch($login: String!) {
  user(login: $login) {
    sponsorshipsAsMaintainer(
      first: 100
      includePrivate: false
      activeOnly: false
    ) {
      nodes {
        isActive
        sponsorEntity {
          ... on User {
            name
            login
            avatarUrl
            url
          }
          ... on Organization {
            name
            login
            avatarUrl
            url
          }
        }
      }
    }
  }
}
