query fetch($cursor: String!) {
    members(after: $cursor) {
        totalCount
        pageInfo {
            endCursor
            hasNextPage
        }
        edges {
            node {
                id
                email
                totalSpendCents
            }
        }
    }
}
