query fetch($cursor: String!) {
    members(after: $cursor, state: ACTIVE) {
        totalCount
        pageInfo {
            endCursor
            hasNextPage
        }
        edges {
            node {
                id
                discordUserId
                email
                fullName
                totalSpendCents
              	subscriptions {
                    id
                    active
                    activatedAt
                    expiresAt
                    coupon {
                        code
                    }
                    orders {
                        createdAt
                        coupon {
                            code
                        }
                    }
                }
            }
        }
    }
}
