query fetch($cursor: String!, $type: ActivityType) {
    activities(after: $cursor, type: $type) {
        totalCount
        pageInfo {
            endCursor
            hasNextPage
        }
        edges {
            node {
                id
                createdAt
              	type
                member {
                    id
                    fullName
                }
            }
        }
    }
}
